### ISSUE TITLE
Remove transformTimeSeriesToTrips and replace trip by timeserie doc

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/coachCO2#26]
On utilise une méthode `transformTimeSeriesToTrips` sur le doc `timeserie` afin de créer ce qu'on appelle un trip, puis on manipule ce trip dans les vues. Mais on a aussi besoin du doc `timeserie` ailleurs (notamment lors de son édition).

L'idée ici est de supprimer le `transformTimeSeriesToTrips` et remplacer les trip qu'on utilise un peu partout par le doc `timeserie`

Approche par étape : 

- [x] mettre `transformTimeseriesToTrips` dans `TripsList` et la supprimer de `Trips`, `LoadedModesList` et `LoadedPurposeList` => https://github.com/cozy/coachCO2/pull/122
- [x] supprimer le besoin de transformer un `timeserie` en trip, et donc passer le `timeserie` de `TripsList` à `TripItem`  => https://github.com/cozy/coachCO2/pull/122
- [x] mémoiser `TripItem` via la revision du `timeserie` => https://github.com/cozy/coachCO2/pull/123
- [x] dans `TripItem`, utiliser une seule méthode qui construirait l’agrégation par déplacement (attribut `aggregation` dans le `timeserie`) qui contiendrait toutes les données nécessaires à l’affichage du `TripItem` et du déplacement (via la vue / modale) => https://github.com/cozy/coachCO2/pull/158
  - [x] on a déjà un début d'agrégation avec `computeAggregatedTimeseries` il faudrait donc compléter les champs manquants pour avoir le schéma suivant : => https://github.com/cozy/coachCO2/pull/133

```
const timeserie = {
  startDate: Date,
  endDate: Date,
  source: String,
  series: Array,
  aggregation: {
    startPlaceName: String,
    endPlaceName: String,
    duration: Number,
    distance: Number,
    calorie: Number,
    co2: Number,
    purpose: Number,
    modes: Array,
    sections: [
      {
        mode: String,
        duration: Number,
        distance: Number,
        avgSpeed: Number,
        startDate: Date,
        endDate: Date,
        co2: Number,
        calorie: Number
      }
    ]
  }
}
```

**Comment by paultranvan** [comment]
https://github.com/cozy/coachCO2/pull/133 implement the evolution of the `timeseries` with the `aggregation` object now stored in database. 
Now, the remaining task to close this issue is to adapt `TripItem` to use timeserie helpers on this `aggregation` object, rather than trip helpers.
