### ISSUE TITLE
Improve AccountProvider

### ISSUE THREAD

**Issue by Merkur39** [cozy/coachCO2#61]
Aujourd'hui le composant `AccountProvider` expose l'état `selectedAccount`, mais la valeur de ce dernier n'est renseignée que lorsque l'utilisateur choisi son compte sur la page `Settings` et est remit à `null` aux rechargement de l'application.

Je propose de :
- Créer un nouveau doctype : `io.cozy.coachco2.settings`
  - Il pourra stocker l'information du compte précédemment sélectionné
- Améliorer le composant `AccountProvider` pour qu'il se règle seul au chargement de l'application, et aux choix de l'utilisateur bien entendu.
- Refactor quelques composants
  - https://github.com/cozy/coachCO2/blob/master/src/components/Views/Trips.jsx
  - https://github.com/cozy/coachCO2/blob/master/src/components/Views/Settings.jsx
  - ...

**Comment by JF-Cozy** [comment]
corrigé ici https://github.com/cozy/coachCO2/pull/90
